### ISSUE TITLE
Missing metrics after installing autoperf

### ISSUE THREAD

**Issue by brnorris03** [HPCL/autoperf#1]
After a clean install at a prefix location, some metrics are not found.

<pre>
norris@compute-0-5:mpi$ autoperf
*** Parsing config files (.autoperf.cfg)... invalid, trying next option...
*** Parsing config files (autoperf.cfg)... done
Traceback (most recent call last):
  File "/home/norris/autoperf/bin/autoperf", line 239, in <module>
    run_experiments()
  File "/home/norris/autoperf/bin/autoperf", line 138, in run_experiments
    experiment.setup()
  File "/home/norris/autoperf/lib/python2.7/site-packages/autoperf/experiment.py", line 323, in setup
    self.metric_set.add(m)
  File "/home/norris/autoperf/lib/python2.7/site-packages/autoperf/utils/MetricSet.py", line 87, in add
    self.add_derived_metric(metric, interval)
  File "/home/norris/autoperf/lib/python2.7/site-packages/autoperf/utils/MetricSet.py", line 53, in add_derived_metric
    for spec in self.get_metric_spec(metric):
  File "/home/norris/autoperf/lib/python2.7/site-packages/autoperf/utils/MetricSet.py", line 28, in get_metric_spec
    with open(spec_file, "r") as f:
IOError: [Errno 2] No such file or directory: '/home/norris/autoperf/lib/python2.7/site-packages/autoperf/utils/metric_spec/FP_INEFFICIENT2'
</pre>

**Comment by brnorris03** [comment]
Added all contents of metric_spec to installation. a737264
