### ISSUE TITLE
Analysis error

### ISSUE THREAD

**Issue by brnorris03** [HPCL/autoperf#6]
If one attempts to run analysis while experiments are not completed yet, the following non-user-friendly error occurs. This should ideally produce either partial analysis results or a more comprehensible message instead of  stack trace.

<pre>
$ autoperf -y
*** Parsing config files (.autoperf.cfg)... invalid, trying next option...
*** Parsing config files (autoperf.cfg)... done
Traceback (most recent call last):
  File "/home11/bnorris2/soft/autoperf/bin/autoperf", line 265, in <module>
    analyze_experiments(options.insnames)
  File "/home11/bnorris2/soft/autoperf/bin/autoperf", line 256, in analyze_experiments
    analyze_an_experiment(exp, insnames)
  File "/home11/bnorris2/soft/autoperf/bin/autoperf", line 244, in analyze_an_experiment
    if is_finished(instance):
NameError: global name 'is_finished' is not defined
</pre>

**Comment by xdai** [comment]
Fixed in 48d5392abb5dff3b08dc8281b4de51b5289c5ab3
